all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
all_joints_names:
- rightFhoof
- rightHhoof
- righthock
- rightFfetlock
- rightHfetlock
- rightknee
- handlerRfoot
- handlerRknee
- nostril
- poll
- withers
- midback
- shoulder
- elbow
- croup
- hip
- stifle
- pointofbuttock
- leftFhoof
- leftHhoof
- lefthock
- leftFfetlock
- leftHfetlock
- leftknee
- handlerLfoot
- handlerLknee
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets\iteration-2\UnaugmentedDataSet_Horse_SkeletonMay17\Horse_Skeleton_M
  Smythe95shuffle1.mat
dataset_type: tensorpack
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: C:\ProgramData\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets\iteration-2\UnaugmentedDataSet_Horse_SkeletonMay17\Documentation_data-Horse_Skeleton_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 26
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
pre_resize: []
project_path: C:\DeepLabCut_Trainings_Master_Folder\Horse_Skeleton-M Smythe-2022-05-17
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
